import isaaclab.sim as sim_utils
from isaaclab.actuators import DelayedPDActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg

from robolab.assets import ISAAC_DATA_DIR

F1_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        asset_path=f"{ISAAC_DATA_DIR}/robots/f1/F1_1.urdf",
        fix_base=False,
        merge_fixed_joints=True,
        activate_contact_sensors=True,
        replace_cylinders_with_capsules=True,
        joint_drive = sim_utils.UrdfConverterCfg.JointDriveCfg(
            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=0, damping=0)
        ),
        articulation_props = sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=True,
            solver_position_iteration_count=8,
            solver_velocity_iteration_count=4,
        ),
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.875),
        joint_pos={
            ".*_hip_pitch_joint": -0.1,
            ".*_knee_joint": 0.2,
            ".*_ankle_pitch_joint": -0.1,
        },
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.90,
    actuators={
        "hip_yaw_roll": DelayedPDActuatorCfg(
            joint_names_expr=[".*_hip_yaw_joint", ".*_hip_roll_joint"],
            stiffness=100.0,
            damping=2.0,
            effort_limit=87.0,
            effort_limit_sim=87.0,
            velocity_limit_sim=5.44,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
        "hip_pitch": DelayedPDActuatorCfg(
            joint_names_expr=[".*_hip_pitch_joint"],
            stiffness=100.0,
            damping=2.0,
            effort_limit=75.0,
            effort_limit_sim=75.0,
            velocity_limit_sim=6.28,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
        "knees": DelayedPDActuatorCfg(
            joint_names_expr=[".*_knee_joint"],
            stiffness=100.0,
            damping=2.0,
            effort_limit=120.0,
            effort_limit_sim=120.0,
            velocity_limit_sim=12.56,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
        "ankle_pitch": DelayedPDActuatorCfg(
            joint_names_expr=[".*_ankle_pitch_joint"],
            stiffness=30.0,
            damping=2.0,
            effort_limit=89.0,
            effort_limit_sim=89.0,
            velocity_limit_sim=17.8,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
        "ankle_roll": DelayedPDActuatorCfg(
            joint_names_expr=[".*_ankle_roll_joint"],
            stiffness=30.0,
            damping=2.0,
            effort_limit=12.0,
            effort_limit_sim=12.0,
            velocity_limit_sim=4.19,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
        "waist": DelayedPDActuatorCfg(
            joint_names_expr=["waist_yaw_joint", "waist_roll_joint"],
            stiffness=100.0,
            damping=2.0,
            effort_limit=87.0,
            effort_limit_sim=87.0,
            velocity_limit_sim=5.44,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
        "shoulder_pitch": DelayedPDActuatorCfg(
            joint_names_expr=[".*_shoulder_pitch_joint"],
            stiffness=30.0,
            damping=2.0,
            effort_limit=48.0,
            effort_limit_sim=48.0,
            velocity_limit_sim=6.28,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
        "shoulder_roll_yaw": DelayedPDActuatorCfg(
            joint_names_expr=[".*_shoulder_roll_joint", ".*_shoulder_yaw_joint"],
            stiffness=30.0,
            damping=2.0,
            effort_limit=84.0,
            effort_limit_sim=84.0,
            velocity_limit_sim=6.07,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
        "forearms": DelayedPDActuatorCfg(
            joint_names_expr=[".*_elbow_joint", ".*_wrist_roll_joint"],
            stiffness=30.0,
            damping=2.0,
            effort_limit=37.0,
            effort_limit_sim=37.0,
            velocity_limit_sim=7.33,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
        "wrist_yaw": DelayedPDActuatorCfg(
            joint_names_expr=[".*_wrist_yaw_joint"],
            stiffness=20.0,
            damping=2.0,
            effort_limit=20.0,
            effort_limit_sim=20.0,
            velocity_limit_sim=6.28,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
        "wrist_pitch": DelayedPDActuatorCfg(
            joint_names_expr=[".*_wrist_pitch_joint"],
            stiffness=20.0,
            damping=2.0,
            effort_limit=25.0,
            effort_limit_sim=25.0,
            velocity_limit_sim=4.44,
            armature=0.01,
            min_delay=0,
            max_delay=2,
        ),
    },
)

F1_LINKS = [
    "pelvis",
    "left_hip_pitch_link",
    "left_hip_roll_link",
    "left_hip_yaw_link",
    "left_knee_link",
    "left_ankle_pitch_link",
    "left_ankle_roll_link",
    "right_hip_pitch_link",
    "right_hip_roll_link",
    "right_hip_yaw_link",
    "right_knee_link",
    "right_ankle_pitch_link",
    "right_ankle_roll_link",
    "waist_yaw_link",
    "torso_link",
    "left_shoulder_pitch_link",
    "left_shoulder_roll_link",
    "left_shoulder_yaw_link",
    "left_elbow_link",
    "left_wrist_roll_link",
    "left_wrist_yaw_link",
    "left_wrist_pitch_link",
    "right_shoulder_pitch_link",
    "right_shoulder_roll_link",
    "right_shoulder_yaw_link",
    "right_elbow_link",
    "right_wrist_roll_link",
    "right_wrist_yaw_link",
    "right_wrist_pitch_link",
]
